### ISSUE TITLE
Replication-controller image pull issue

### ISSUE THREAD

**Issue by mohammad-ammar14** [open-component-model/replication-controller#14]
I am trying to deploy replication controller to the kind cluster. There is some error in pulling the image #eroor imagePullBackOf.
Even it is not able to pull the image using docker pull command.

**Comment by Skarlso** [comment]
What was the error? Can we close this issue now? @mohammad-ammar14

**Comment by mohammad-ammar14** [comment]
Issue has fixed by @phoban01, you can put comments and close
