### ISSUE TITLE
Signing Support in Replication Controller

### ISSUE THREAD

**Issue by phoban01** [open-component-model/replication-controller#38]
## Description

The replication controller should support creating new signatures to signify that a component has been replicated and "accepted" / "approved" within the destination environment. 

This will allow for scenarios where downstream consumers (such as the ocm-controller) can simply trust an internal signature rather than needing access to external public keys or identities.

**Comment by Skarlso** [comment]
https://github.com/open-component-model/replication-controller/pull/89

**Comment by Skarlso** [comment]
https://github.com/open-component-model/mpas-product-controller/pull/91

**Comment by Skarlso** [comment]
https://github.com/open-component-model/ocm-controller/pull/324 release for signing support.
